language: node_js
os: linux
node_js:
  - "13"

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-5

services: mongodb
env:
  global:
  - AUTH_DISABLED=yes
  - VERSION=0.0.1
  - AUTHOR="TESTS"
  - LANGUAGUE="TESTS"
  - TYPE="TESTS"
  - FRAMEWORK="KoaJS-TESTING ENVIROMENT"
  - LOG_REQUESTS=false
  - DB_HOST=127.0.0.1
  - DB_PORT=27017
  - DB_USERNAME=user
  - DB_PASSWORD=password
  - DB_NAME=mydb_test
  - TWILIO_FROM=myBlog
  - JWT_SECRET=secret
  - JWT_EXP_MINUTES=10
  - SALT_ROUNDS=10
  - PORT=8080

before_install:
  - npm install -g node-gyp

before_script:
  - sleep 15
  - mongo mydb_test --eval 'db.createUser({user:"user",pwd:"password",roles:["readWrite"]});'
  - npm install
  - npm install tslint typescript --save-dev
  - tslint -p '.'

jobs:
  include:
    - stage: Unit Tests
      script: npm test
    - stage: Interation Tests
      script: npm run test-integration
