# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Install npm depedencies  
      run: npm i
      
    - name: Run Unit Tests
      run: npm test
      
    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.3.0
      with:
        mongodb-version: 4.2
        
    - name: Run Integration Tests
      run: npm run test-integration
      env:
        AUTH_DISABLED: yes
        VERSION: 0.0.1
        AUTHOR: "TESTS"
        LANGUAGUE: "TESTS"
        TYPE: "TESTS"
        FRAMEWORK: "KoaJS-TESTING ENVIROMENT"
        LOG_REQUESTS: false
        DB_HOST: 127.0.0.1
        DB_PORT: 27017
        DB_USERNAME: ""
        DB_PASSWORD: ""
        DB_NAME: mydb_test
        TWILIO_SID: ${{ secrets.TWILIO_SID }}
        TWILIO_TOKEN: ${{ secrets.TWILIO_TOKEN }}
        TWILIO_FROM: myBlog
        JWT_SECRET: secret
        JWT_EXP_MINUTES: 10
        SALT_ROUNDS: 10
        PORT: 8080
      
